
-- Full Project Broker schema (final)
create extension if not exists pgcrypto;
create table if not exists profiles (id uuid primary key default gen_random_uuid(), full_name text, email text, role text, skills text[], is_approved boolean default false, created_at timestamptz default now());
create table if not exists projects (id uuid primary key default gen_random_uuid(), owner_id uuid references profiles(id), project_name text, description text, project_type text, categories text[], inspiration_photos text[], created_at timestamptz default now());
create table if not exists ads (id uuid primary key default gen_random_uuid(), project_id uuid references projects(id), category text, description text, is_emergency boolean default false, emergency_fee numeric default 850, bid_closes_at timestamptz, status text, contractor_id uuid, created_at timestamptz default now());
create table if not exists bids (id uuid primary key default gen_random_uuid(), ad_id uuid references ads(id), contractor_id uuid references profiles(id), amount numeric, timeline_days int, details text, created_at timestamptz default now());
create table if not exists contractor_boq (id uuid primary key default gen_random_uuid(), ad_id uuid references ads(id) on delete cascade, contractor_id uuid references profiles(id), items jsonb, total numeric, notes text, submitted_at timestamptz default now());
create table if not exists contracts (id uuid primary key default gen_random_uuid(), job_id uuid references ads(id), customer_id uuid references profiles(id), contractor_id uuid references profiles(id), contract_type text, contract_text text, signed_by_customer boolean default false, signed_by_contractor boolean default false, signed_at_customer timestamptz, signed_at_contractor timestamptz, created_at timestamptz default now());
create table if not exists ratings (id uuid primary key default gen_random_uuid(), job_id uuid references ads(id), customer_id uuid references profiles(id), contractor_id uuid references profiles(id), quality int, contractor_experience int, platform_experience int, comments text, created_at timestamptz default now());
create table if not exists snag_list (id uuid primary key default gen_random_uuid(), ad_id uuid references ads(id), inspector_id uuid references profiles(id), contractor_id uuid references profiles(id), description text, photos text[], is_resolved boolean default false, created_at timestamptz default now(), resolved_at timestamptz);
create table if not exists contractor_finances (id uuid primary key default gen_random_uuid(), contractor_id uuid references profiles(id), amount numeric, type text, description text, file_url text, created_at timestamptz default now());
create table if not exists invoices (id uuid primary key default gen_random_uuid(), contractor_id uuid references profiles(id), job_id uuid references ads(id), file_url text, created_at timestamptz default now());
create table if not exists scoper_requests (id uuid primary key default gen_random_uuid(), requester_id uuid references profiles(id), address text, notes text, fee numeric default 400, created_at timestamptz default now());
